export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const IS_LOGGED_IN_SUCCESS = "IS_LOGGED_IN_SUCCESS";
export const IS_LOGGED_IN_FAILURE = "IS_LOGGED_IN_FAILURE";

export const ADD_JOB = "ADD_JOB";
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";
export const ADD_JOB_FAILURE = "ADD_JOB_FAILURE";

export const GET_JOBS = "GET_JOBS";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";

export const GET_JOB = "GET_JOB";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const GET_JOB_FAILURE = "GET_JOB_FAILURE";

export const SET_UP_STUDENT_PROFILE = "SET_UP_STUDENT_PROFILE";
export const SET_UP_STUDENT_PROFILE_SUCCESS = "SET_UP_STUDENT_PROFILE_SUCCESS";
export const SET_UP_STUDENT_PROFILE_FAILURE = "SET_UP_STUDENT_PROFILE_FAILURE";

export const SET_UP_COMPANY_PROFILE = "SET_UP_COMPANY_PROFILE";
export const SET_UP_COMPANY_PROFILE_SUCCESS = "SET_UP_COMPANY_PROFILE_SUCCESS";
export const SET_UP_COMPANY_PROFILE_FAILURE = "SET_UP_COMPANY_PROFILE_FAILURE";

export const SET_USER = "SET_USER";

export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";
// export const SET_UP_COMPANY_PROFILE = 'SET_UP_COMPANY_PROFILE'
// export const SET_UP_COMPANY_PROFILE_SUCCESS = 'SET_UP_COMPANY_PROFILE_SUCCESS'
// export const SET_UP_COMPANY_PROFILE_FAILURE = 'SET_UP_COMPANY_PROFILE_FAILURE'

// export const GET_USERS = 'GET_USERS'
// export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
// export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'
